-- Número de identificação da viagem (exibido como "Viagem #12"): facilita
-- achar uma viagem específica, por exemplo ao indicar o condutor de uma multa.
alter table public.trips add column if not exists trip_number bigint generated by default as identity;
create unique index if not exists trips_trip_number_key on public.trips (trip_number);

-- Ponto exato da infração, marcado no mapa pelo gestor.
alter table public.infractions add column if not exists lat double precision;
alter table public.infractions add column if not exists lng double precision;
