-- 20260604021615_security_revoke_internal_functions
--
-- MIGRATION APLICADA EM PRODUÇÃO SEM PASSAR PELO REPOSITÓRIO.
-- Este arquivo existe para o histórico local bater com o do banco; o SQL real
-- está preservado em supabase_migrations.schema_migrations e NÃO foi apagado.
--
-- Para recuperar o SQL original desta migration:
--   select unnest(statements) from supabase_migrations.schema_migrations
--    where version = '20260604021615';
--
-- Não reaplique: já consta como aplicada no banco.
